name: linuxpkgmanager
version: '1.0.0'
summary: Modern GUI to manage manually installed APT & Snap packages
description: |
  LinuxPkgManager is a desktop application that displays only the packages
  you manually installed — filtering out system packages, libraries and
  Ubuntu base components. Supports APT and Snap  with a dark professional UI.
grade: stable
confinement: classic
base: core22
architectures:
  - build-on: amd64

apps:
  linuxpkgmanager:
    command: bin/python3 $SNAP/bin/pkgmanager
    desktop: usr/share/applications/linuxpkgmanager.desktop

parts:
  linuxpkgmanager:
    plugin: python
    source: .
    python-packages:
      - PyQt6
    stage-packages:
      - python3.10
      - python3-pip
      - libgl1
      - libglib2.0-0
      - libdbus-1-3
      - libxcb-cursor0
      - libxcb1
      - libx11-6
      - libxext6
      - libxrender1
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/usr/share/applications
      mkdir -p $CRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps
      cp $CRAFT_PROJECT_DIR/snap/local/linuxpkgmanager.desktop \
         $CRAFT_PART_INSTALL/usr/share/applications/
      cp $CRAFT_PROJECT_DIR/assets/icon.png \
         $CRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps/linuxpkgmanager.png

layout:
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/share/applications:
    bind: $SNAP/usr/share/applications